---

- name: Download Java
  command: "wget -q -O /opt/jdk-8u5-linux-x64.tar.gz --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz creates=/opt/jdk-8u5-linux-x64.tar.gz"

- name: Unpack archive
  command: "tar -zxf /opt/jdk-8u5-linux-x64.tar.gz -C /opt creates=/opt/jdk1.8.0_05"

- name: Fix ownership
  file: state=directory path={{java_name}} owner=root group=root recurse=yes

- name: Make Java available for system
  command: 'alternatives --install "/usr/bin/java" "java" "/opt/jdk1.8.0_05/bin/java" 2000'

- name: Clean up
  file: state=absent path=/opt/jdk-8u5-linux-x64.tar.gz

- name: Add Elasticsearch GPG key.
  rpm_key:
    key: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository.
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0644

- name: Install Elasticsearch.
  yum: name={{ item }} state=present
  with_items:
     - elasticsearch
